### PR TITLE
Mifare Classic dump reading on PN532_BLE and new Startup Menu

### PR DESCRIPTION
**Pull request by whywilson**

### CODE REVIEW

**Comment by rennancockles** [comment]
For this PR I think you can remove the startMenuIndex logic and leave only the RFID related. 

If we decide for creating something like this startMenuIndex stuff we would have to think on a better way to develop this, since the way it is now it's introducing logic duplication and config.cpp and setting.cpp knows too much about the MainMenu internal stuff

**Comment by whywilson** [comment]
Got it. I'll close this pr and only include the RFID related.

**Comment by pr3y** [comment]
Awesome @whywilson, thanks again for contributing.
I gonna close this PR now, in the next PR with only RFID releated also don't forget to remove the commit hash for you lib in platformio.ini

**Comment by whywilson** [comment]
Go it. Thank you for the reminding.

**Pull request closed without merging**
