### PR TITLE
fix ir_read.cpp

### PR DESCRIPTION
**Pull request by MayLaOwn**
ir reader fix, now raw is forced and sending works without problems.

#### Proposed Changes ####

I created a new branch and modified the read_signal() function to force RAW mode, in order to avoid errors in reading the signal. I also made some small adjustments as you can see. Now it works without problems, I tested it on two remote controls that until this afternoon did not work with the beta version. I hope to help you in this amazing project.

### CODE REVIEW

**Comment by bmorcelli** [comment]
Can you please keep comments in English?

**Comment by bmorcelli** [comment]
And keep the GitHub link as a code reminder

**Comment by MayLaOwn** [comment]
yes, I corrected the language to English

**Comment by Lamnxzp** [comment]
I don't think like removing decoded protocols from IR Read is a "ir reader fix".
If something isn't working correctly, we should fix that, and not remove the whole thing lol

**Comment by bmorcelli** [comment]
> I don't think like removing decoded protocols from IR Read is a "ir reader fix". If something isn't working correctly, we should fix that, and not remove the whole thing lol

I quite agree with you.. but debug the irsend lib would take ages.. it is always better save/repply raw codes than RAW->Decode-> Encode->Decode-Send

**Pull request merged**
