### PR TITLE
added support for cc1101 raw send (#66) + more debug serial cmds

### PR DESCRIPTION
**Pull request by eadmaster**
Tested only with sending decoded rf signals.

### CODE REVIEW

**Comment by IncursioHack** [comment]
[Test Bruce] 1.3.1 /249 - Dev - https://github.com/pr3y/Bruce/actions/runs/10333329029
[Version/Artifact] Bruce_m5stack-cplus1_1_249
[Datetime] 08/10/2024 - 21:50 [GMT-3]
[Device] StickC Plus 1.1

* Scan/Copy -> It worked perfectly, saving the file in the FS: BruceRF/bruce_0.sub
* Custom SubGhz -> Transmitted correctly, received by Cardputer with RF433T and noticed on Radio Quansheng
* Jammer Itmt -> It worked as shown in the video, the pattern is too subtle to be clearly noticed by the Spectrum
* Jammer Full -> It worked as shown in the video, the pattern is too subtle to be clearly noticed by the Spectrum

* Spectrum -> This was the only one I had no luck with, it keeps the Spectrum intact, even using some control or sending data with the Cardputer via the RF433T

Would you like me to test something specific?

**Comment by eadmaster** [comment]
i forgot Spectrum needs to be updated too,

btw i've found [this issue that suggests to swap a few things around](https://github.com/LSatan/SmartRC-CC1101-Driver-Lib/issues/122#issuecomment-1872568284), let's try that (wait for the next push).

**Comment by IncursioHack** [comment]
[Test Bruce] 1.3.1 /250 - Dev - https://github.com/pr3y/Bruce/actions/runs/10336396213
[Version/Artifact] Bruce_m5stack-cplus1_1_250
[Datetime] 08/10/2024 - 23:55 [GMT-3]
[Device] StickC Plus 1.1

* Spectrum

Only the Spectrum was tested with the CC1101 on the StickC Plus 1.1, according to the videos sent on Discord, it apparently managed to capture signals at both 433.92 Mhz and 315 Mhz (this range was used as an example).

Excellent work eadmaster, you and the team are incredible.

**Comment by IncursioHack** [comment]
[Test Bruce] 1.3.1 /250 - Dev - https://github.com/pr3y/Bruce/actions/runs/10336396213
[Version/Artifact] Bruce_m5stack-cardputer_250
[Datetime] 08/11/2024 - 00:10 [GMT-3]
[Device] Cardputer

Spectrum
The Spectrum is working perfectly on the Cardputer with the RF433R (433.92Mhz).

**Pull request merged**
