### PR TITLE
RFID Support to PN532

### PR DESCRIPTION
**Pull request by rennancockles**
#### Proposed Changes ####

- Add DevMode config (can be enabled in bruce.conf) with I2C address finder
- Add support to PN532 using both SPI and I2C on Tag-O-Matic

#### Types of Changes ####

New Feature

### CODE REVIEW

**Comment by Ademolght** [comment]
and how you want PN532 on cardputer?

**Comment by IncursioHack** [comment]
> and how you want PN532 on cardputer? And is it going to emulate rfid or nfc card?


Friend, have a little patience, he has just implemented PN532, some tests will be necessary, another point is that the only code reference available to emulate PN532 (SeedStudio) is not fully refined and several adjustments will be needed.
But I advise that you don't expect the same behavior as the Flipper, considering that it uses another card for reading, writing and NFC emulation.

**Comment by Ademolght** [comment]
yes but you can also do a connection via HSU (High Speed UART) but i don't think M5stack product can do this

**Comment by rennancockles** [comment]
@Ademolght feel free to contribute and develop some stuff too. It'll be awesome to have more people helping with Bruce's features since we all have work and a life to live. We dedicate our time to this project without receiving anything in return, just for the pleasure of contributing. I’ve been seeing you criticizing and questioning a bunch of stuff but haven’t seen you creating anything to help.

**Comment by Ademolght** [comment]
i am dev a bitcoin price checker for bruce and sms spoof so calm down

**Comment by IncursioHack** [comment]
> _@rennancockles_ i am dev a bitcoin price checker for bruce and sms spoof so calm down

Develop something, then we'll talk. :) We look forward to your contribution <3

**Comment by rennancockles** [comment]
pn532i2c
PN532 I2C connection schema

**Comment by rennancockles** [comment]
pn532spi
PN532 SPI connection schema

**Comment by 666Sleepy666** [comment]
I have a question does the Bruce firmware supports pn532 v 2.0

**Comment by rennancockles** [comment]
If it has pins to connect it through SPI or I2C it'll probably work. If it only has the usb port, then no

**Comment by DMA3002** [comment]
How to fix "Failed to read data blocks"? (I2C connection)

**Comment by rennancockles** [comment]
@mountain276 this is not the best place to post issues. Try creating an issue or sending a message on our discord next time. 

Regarding your error, try holding your tag near the reader a little longer. Reading all data blocks takes a few seconds to complete. A mifare 1K for instance has 64 blocks with 16 bytes each, hence 1024 bytes (1K).

**Pull request merged**
