### PR TITLE
New features for Bruce

### PR DESCRIPTION
**Pull request by valentin8709**
Hi, 
Here is my pull request, with following changelog (mainly for M5StickC Plus 2).

**Fixes**
- [x] center Bruce and version to splashscreen for better UI
- [x] set & display clock from RTC
- [x] UI bug fixes (like Wifi info drawn on top of the UI boders)
- [x] return to main menu fixed and added when missing
- [x] better shutdown to avoir rolling menu (code from M5 demo)
- [x] add little tone / bip at startup (just because it can, and can be bypassed if key pressed while booting) 

**Customizations & features**  

**Clock**
- [x] new clock icon
- [x] clock redraw for a slightly better one

**WiFi**
- [x] add default ssid and password (values: Mobile-AP / mobile-ap) on WiFi connect (to not type pwd on M5StickC Plus 2)
- [x] add password (brucenet) to WiFi AP feature, and add QRCode to connect to it (more secure and easy to connect with QRCode)

**BLE**
- [x] simple BT connection (code from M5 demo)
- [x] BLE recon / scanner 

**Others**
- [x] QRCodes display (code from Nemo) (BruceAP, RickRoll, HackerTyper, ZomboCom)
- [x] Mic spectrum (code from M5 demo)

Closes issue #74

### CODE REVIEW

**Comment by Niximkk** [comment]
Device: M5StickC Plus 1.1

I don't know what BLE Connect is supposed to do, I tried to connect using my phone and, even before pairing, it started sending codes (??). Also the UI is broken. After the second time, it starts showing the codes before the menu is loaded with a small text in the middle.

The QR code restarted my StickC Plus 1.1 the first two times and after the brightness was reduced for some reason.

You should be able to leave the Mic spectrum pressing any button, not only power.

The clock is off center.

Those are all the problems I encountered. I loved the "little tone/beep on startup", they are not game-changing features, but they are very useful!

**Comment by valentin8709** [comment]
Thanks @Niximkk for you feedback !

The BT Connect is just a demo / dev feature to connect M5 to other device. It sends codes to make a test, or eventually to bruteforce commands on a BT device.

I will check the code for the bugs you encountered.

When you say "the clock is off center" : do you mean the icon in the menu ? The clock in the top left corner ? or the clock itself when full displayed ?

Thanks again :)

**Comment by Niximkk** [comment]
Hello @valentin8709, about the clock, this is what i mean.

**Comment by valentin8709** [comment]
Arf ! Okay I will test taking better constant values (screen of M5Stick 1.1 must be slightly different than 2).

**Comment by Niximkk** [comment]
The clock is wrong btw, it changes everytime i boot for some reason

**Comment by valentin8709** [comment]
> The clock is wrong btw, it changes everytime i boot for some reason

Yes it seems that RTC hardware is not the same between versions. I think it's for this reason the clock was not displayed by default in Bruce. My RTC fix only works on M5StickC Plus 2. You can connect to a wifi to get NTP time. Did you try to set the time manually (in config) ? Does it survive a reboot ?

**Comment by Niximkk** [comment]
> You can connect to a wifi to get NTP time.

I did, it didn't survive the reboot, wasn't the rtc clock working already?

**Comment by valentin8709** [comment]
I don't know for M5StickC Plus 1.1 (I do not have one). But for M5StockC Plus 2 it wasn't working. 
The only thing working was NTP / manually adjust, but it wasn't surviving reboot.

I am understanding better now : I've added checks to display clock from RTC hardware in C Plus 2, and did not change anything else. Therefore when you enter clock menu, your device display a wrong time, without seconds. It's the missing seconds that make the clock off center.

**Comment by Niximkk** [comment]
check nemo's source code, it has the correct configuration for all devices

**Comment by bmorcelli** [comment]
Problem is that Nemo uses M5 libs.. and we are not using them at them.. so it needs to be implemented differently

**Comment by valentin8709** [comment]
About the other bugs :
- While displaying a QR Code, the brightness was set to 100% for better readabiliy, then set to 25% after. It is now saving user config to set the old value, and not an arbitrary one.
- You can quitt mic spectrum by pressing "Esc" or "Sel" key
- The bug on BLE connect (bad display / disconnect on the second connection) is fixed

**Comment by Niximkk** [comment]
> Problem is that Nemo uses M5 libs.. and we are not using them at them.. so it needs to be implemented differently

i see, the 1.1 is the only device com esse problema ne? KKKKKKKK cansei de falar ingles :P

**Comment by valentin8709** [comment]
> > Problem is that Nemo uses M5 libs.. and we are not using them at them.. so it needs to be implemented differently
> 
> i see, the 1.1 is the only device com esse problema ne? KKKKKKKK cansei de falar ingles :P

It seems yes =/ Sorry I can speak french also but it will not help I think ^^

**Comment by Niximkk** [comment]
@bmorcelli is brazilian too, sorry for that, im in the middle of a cs2 faceit match :P

**Comment by Niximkk** [comment]
i will take a look at the code, 1 sec

**Comment by bmorcelli** [comment]
I was looking into M5 RTC lib for M5StickC Plus 1.1, and is the same you used.. 

the wrong clock isn't related to timezone setting?

**Comment by Niximkk** [comment]
uuuh no, its random i guess, 5AM -> reboot -> 10AM

**Comment by valentin8709** [comment]
RTC Lib is used only if flag M5StickC Plus 2 is set (using `#if defined(STICK_C_PLUS2)`), in any other case, the old behaviour is running.
Perhaps I can use `#if defined(STICK_C_PLUS) || defined(STICK_C_PLUS2)` instead ?

**Comment by bmorcelli** [comment]
Yes, I think it worth the test..

**Comment by valentin8709** [comment]
I just apply RTC fix for M5StickC Plus too. Could you test it @Niximkk ?
Your clock should survive a reboot after a manual / NTP set, be displayed in the header and at startup.

**Comment by Niximkk** [comment]
uuuh, send me the artifact

**Comment by valentin8709** [comment]
> uuuh, send me the artifact

You can test with the last commit of this branch, I think RTC should work fine.

**Comment by Niximkk** [comment]
The RTC works, but the NTP Adjust broke

**Pull request merged**
