### PR TITLE
Added TR Language and some code refactoring

### LINKED ISSUE #491: Interface optimization
Hello, I want to ask you to optimize the interface. There are extra sections that need to be removed to the Others tab: Scripts (it definitely shouldn't be on the main page), Clock (a function that may be useless on some devices, for example CYD, after each shutdown, time data is erased), Connect (a function that is quite useful, but not in demand due to bugs).
And now about the sections that should be added to the main page: Bad KB(must be added to the main page, and must contain BadUSB and BadBLE).

Please do it😀

### PR DESCRIPTION
**Pull request by 9dl**
#### Proposed Changes ####
This pull request refactors and optimizes the interface based on issue [#491](https://github.com/pr3y/Bruce/issues/491). It introduces a new **Bad Devices** menu on the main page, which consolidates **Bad USB** and **Bad BLE** into a single section. The following changes are also made:

Resolved conflict between CH9329 and BleKeyboard.
Additionally, the code was **refactored and cleaned up** for improved readability and maintainability.

#### Types of Changes ####
- **New Feature**: Added **Bad KB** to the main page and refactored existing features.
- **Fix bug**: Resolved conflict between CH9329 and BleKeyboard.
- **Code Refactoring**: Improved code readability and maintainability.

#### Verification ####
- Navigate to the main menu and verify that **Bad Devices** is now visible, containing both **Bad USB** and **Bad BLE** features.

#### Testing ####

- Has been tested on CYD.

#### Linked Issues ####
- Resolves https://github.com/pr3y/Bruce/issues/491.

#### User-Facing Change ####
```release-note
- Added a new **Bad Devices** menu to the main page containing **Bad USB** and **Bad BLE**.

```

#### Further Comments ####
-/-

### CODE REVIEW

**Comment by 9dl** [comment]
I dont really get the issue with other platforms, if any other contributor could help would be great.

**Comment by 9dl** [comment]
Works now on all platform but the section only has Bad USB (originally was in Other section). Tested on CYD.

**Comment by 9dl** [comment]
Types of Changes
- Added TR Layout
- Made the Names of the Keyboard Layout Menu better

**Comment by pr3y** [comment]
Hey @9dl thanks for contributing!
I liked the TK layout adding and the refactor, but idk about the icon for Bad devices being a bowling ball... also wasnt Bad BLE supposed to be on this menu?
its important to add that the firmware currently already have keybindings to go to some functions (like press 'b' for badUSB) while on main menu and even has the option to select a function to run as soon as it boots.
I dont see a reason for a menu just for 'Bad devices' for now, it could be added if some different icon or something to do with it, also 'Bad devices' can be confusing to end-user maybe

**Comment by 9dl** [comment]
Yeah, the bowling ball was supposed to be a skull, haha. I'm not really great at designing icons, so it was a placeholder. As for Bad BLE, I ran into a lot of issues trying to combine it with Bad USB on other platforms. The keyboard libraries kept conflicting, and I couldn’t find a solid workaround.
For the menu, you make a good point. It might be better to skip the "Bad devices" menu for now. Thanks for the feedback! 😊

**Comment by 9dl** [comment]
Types of Changes
- New Feature: Added TR Language
- Fix bug: Resolved conflict between CH9329 and BleKeyboard Libary.
- Code Refactoring: Improved code readability and maintainability.

**Comment by 9dl** [comment]
@pr3y I changed everything back to normal. 👍

**Comment by pr3y** [comment]
Awesome! looks good to me now, feel free to join our discord
Only thing is that the first part of bad_usb.cpp could be more readable maybe with tabs but i gonna merge it anyways
Thanks again for contributing

**Pull request merged**
