### PR TITLE
Add custom QrCode saving

### PR DESCRIPTION
**Pull request by MyMindWorld**
#### **Proposed Changes**
This MR introduces the ability to **save custom QR codes** to the configuration file (`bruce.conf`) for a faster and more convenient way to display frequently used QR codes.

Additionally, users can **remove default QR codes** from the system. 

---

#### **Types of Changes**
- **New Feature**: 
  - Ability to **save custom QR codes** to the configuration file (`bruce.conf`).
  - Ability to **remove pre-configured default QR codes** directly from the UI.

---

#### **Verification**
All changes are accessible via the **Other → QR Codes** menu.

**Previous Behavior:**
- A static, hardcoded list of QR codes was displayed, which included:
  - "Bruce AP"
  - "Bruce Repo"
  - "Rickroll"
  - "HackerTyper"
  - "ZomboCom"

**New Behavior:**
- The list of QR codes is now **loaded dynamically from the configuration file (`bruce.conf`)**.
- By default, the list in the `qrCodes` array has the same entries as before.
- Any QR code can now be **added, removed, or customized**.

---

#### **New Options in the Custom Menu**
Within the **Custom** menu, users have access to the following options:

- **Display**:  
  Write text and generate a QR code dynamically.  

- **Save & Display**:  
  Write a name and content for a QR code, **save it to the configuration**, and display it. Saved QR codes can be accessed via the main **QR Codes** menu.  

- **Remove**:  
  Select and **delete any saved QR code**, including default QR codes.  

- **Back**:  
  Return to the main **QR Codes** menu.

---

#### **Testing**
Tested on an **M5Stack-CPLUS2** device under the following scenarios:
- **Update from previous version**: Ensured all existing functionality remained intact.  
- **Fresh install**: Verified the default list of QR codes loaded correctly.  
- **Adding new QR codes**: Successfully saved and displayed QR codes using the new **Save & Display** option.  
- **Removing QR codes**: Successfully removed default and user-added QR codes from the system.

---

#### **Linked Issues**
None

---

#### **User-Facing Changes**
```release-note
- Introduced the ability to save custom QR codes and remove default ones.
```

### CODE REVIEW

**Review by pr3y — COMMENTED** [review]
Awesome! thanks for contributing!
i was thinking about adding "Bruce Wiki" and "bruce.computer" on the static hardcoded list also, something like:
`{"Bruce Wiki", "https://github.com/pr3y/Bruce/wiki"},
 {"Bruce Site", "https://bruce.computer"},`

**Comment by MyMindWorld** [comment]
Thanks for the feedback and suggestion!

With this new options I think it might be a good idea to trim the list slightly. Otherwise, the list could become too large, making it harder for users to discover the Custom option.

Current list is:

```
{"Bruce AP", "WIFI:T:WPA;S:BruceNet;P:brucenet;;"},
{"Bruce Repo", "https://github.com/pr3y/Bruce"},
{"Rickroll", "https://youtu.be/dQw4w9WgXcQ"},
{"HackerTyper", "https://hackertyper.net/"},
{"ZomboCom", "https://html5zombo.com/"}
```

And I propose something like:

```
{"Bruce AP", "WIFI:T:WPA;S:BruceNet;P:brucenet;;"},
{"Bruce Wiki", "https://github.com/pr3y/Bruce/wiki"}, 
{"Bruce Site", "https://bruce.computer"},
{"Rickroll", "https://youtu.be/dQw4w9WgXcQ"}
```
Without separate repo link, because advanced users will recognize git anyway.

That said, I’m not hard on this point. If you feel it’s better to keep all of the current options and add this new ones, I’m happy to do that instead. Let me know what you think!

**Comment by pr3y** [comment]
Really good!
The way you proposed its perfect for me, i didnt liked hackertype or zombocom QRs either :v

**Comment by MyMindWorld** [comment]
They are gone now 😄

**Comment by SpiritDetect** [comment]
Hi, I wanted some information. I just installed the firmware, but in the others mode I can't find SD card, LittleFs and WebUi. May I know the reason for this? thank you so much

**Pull request merged**
