### PR TITLE
UNIVERSAL TV CONTROLLER

### PR DESCRIPTION
**Pull request by ironweb10**
Check If this works please
🥺🥺🥺🥺

### CODE REVIEW

**Comment by bmorcelli** [comment]
It doesn't work

**Comment by ironweb10** [comment]
Can u send a vid

**Comment by ironweb10** [comment]
Please

**Comment by bmorcelli** [comment]
Your code didn't even compile

**Comment by ironweb10** [comment]
XDDDDDDDDD

**Comment by ironweb10** [comment]
What problems have?
I only added a .cpp and a .h file

**Comment by IncursioHack** [comment]
https://github.com/pr3y/Bruce/pull/468/checks#step:6:268

**Pull request closed without merging**
