### PR TITLE
added power serial cmds, wakeup cardputer by pressing any key (#64)

### PR DESCRIPTION
**Pull request by eadmaster**
also fixed "tts" command typo

### CODE REVIEW

**Comment by eadmaster** [comment]
not sure what caused this:

````
/home/runner/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/m5stack-cplus2/firmware.elf section `.iram0.text' will not fit in region `iram0_0_seg'
/home/runner/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: IRAM0 segment data does not fit.
/home/runner/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: region `iram0_0_seg' overflowed by 2264 bytes
````

**Comment by Niximkk** [comment]
Uhhh...

https://github.com/espressif/esp-idf/issues/6914
https://github.com/espressif/esp-idf/issues/8609
https://esp32.com/viewtopic.php?t=22130

Maybe this could help you

**Comment by Niximkk** [comment]
> If the app allocates more static IRAM than available, then the app will fail to build, and linker errors such as section '.iram0.text' will not fit in region 'iram0_0_seg', IRAM0 segment data does not fit, and region 'iram0_0_seg' overflowed by 84-bytes will be seen. If this happens, it is necessary to find ways to reduce static IRAM usage in order to link the application.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/ram-usage.html#optimize-iram-usage

Any idea what could have caused it?

**Comment by eadmaster** [comment]
my only hypothesis is this new symbol i've added in the code `esp_deep_sleep_start()`.

**Comment by Niximkk** [comment]
prob... I believe that the m5 libraries have a power off function.

**Comment by eadmaster** [comment]
> m5 libraries have a power off function.

i couldn't find any, deepsleep is closest thing .
https://github.com/esp8266/Arduino/issues/929
https://esp32.com/viewtopic.php?t=5624

**Comment by Niximkk** [comment]
Power:
        M5.Power.setPowerBoostKeepOn()
        M5.Power.setCharge(uint8_t mode);
        M5.Power.setPowerBoostKeepOn(bool en);
        M5.Power.isChargeFull();
        M5.Power.setWakeupButton(uint8_t button);
        M5.Power.powerOFF();

**Comment by Niximkk** [comment]
on https://github.com/m5stack/M5Stack/blob/master/src/M5Stack.h

**Comment by Niximkk** [comment]
void M5Stack::powerOFF() {
    M5.Power.deepSleep();
}

**Comment by Niximkk** [comment]
```c
void POWER::deepSleep(uint64_t time_in_us) {
    // Keep power keep boost on
    setPowerBoostKeepOn(true);

    // power off the Lcd
    M5.Lcd.setBrightness(0);
    M5.Lcd.sleep();

    // ESP32 into deep sleep
    esp_sleep_enable_ext0_wakeup((gpio_num_t)_wakeupPin, LOW);

    if (time_in_us > 0) {
        esp_sleep_enable_timer_wakeup(time_in_us);
    } else {
        esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_TIMER);
    }

    while (digitalRead(_wakeupPin) == LOW) {
        delay(10);
    }

    (time_in_us == 0) ? esp_deep_sleep_start() : esp_deep_sleep(time_in_us);
}
```

**Comment by eadmaster** [comment]
internally, both `M5.Power.deepSleep` and `powerOFF` are still calling `esp_deep_sleep_start`, not sure if it will make any difference for this issue
https://github.com/m5stack/M5Stack/blob/master/src/utility/Power.cpp#L449

(My guess is i have to remove the call to `esp_deep_sleep_start()` completely.)

**Comment by pr3y** [comment]
Whats the issue on using what is already on src/core/PowerSave.cpp? is deep sleep better somehow?
```cpp
/* Put device on sleep mode */
void sleepModeOn(){
  isSleeping = true;
  setCpuFrequencyMhz(80);
  turnOffDisplay();
  delay(200);
}

/* Wake up device */
void sleepModeOff(){
  isSleeping = false;
  setCpuFrequencyMhz(240);
  getBrightness();
  delay(200);
}
```

**Comment by eadmaster** [comment]
> Whats the issue on using what is already on src/core/PowerSave.cpp? is deep sleep better somehow?
> 
> ```c++
> /* Put device on sleep mode */
> void sleepModeOn(){
>   isSleeping = true;
>   setCpuFrequencyMhz(80);
>   turnOffDisplay();
>   delay(200);
> }
> 
> /* Wake up device */
> void sleepModeOff(){
>   isSleeping = false;
>   setCpuFrequencyMhz(240);
>   getBrightness();
>   delay(200);
> }
> ```

that's different, i am already using that code for the `power sleep` command btw.

**Comment by bmorcelli** [comment]
Deep sleep doesn't work properly on the StickCs, because they need to set up the RTC chip to "wake up", and it will work more like a turn-off with scheduled event,... so i don't recommend

to turn off the StickCs we can use:
StickC puls 1.1:
axp192.PowerOff();

StickC Plus 2:
digitalWrite(4, LOW);

for the cardputer I must do some research here

**Comment by eadmaster** [comment]
> for the cardputer I must do some research here

for the cardputer i've found `esp_deep_sleep_start()`  without setting up the RTC wakeup it is very close to a "software poweroff" (e.g. you can only power-cycle/reset the device to restart)

**Comment by bmorcelli** [comment]
```
  if(cmd_str == "power off" ) {
    // closest thing https://github.com/esp8266/Arduino/issues/929
    //ESP.deepSleep(0);
    #if defined(STICK_C_PLUS)
    axp192.PowerOff();
    #elif defined(STICK_C_PLUS2)
    digitalWrite(4,LOW);
    #else
    esp_deep_sleep_start();  // only wake up via hardware reset
    #endif
    return;
  }
```

This fixed the problem here for me

**Comment by eadmaster** [comment]
> ```
>   if(cmd_str == "power off" ) {
>     // closest thing https://github.com/esp8266/Arduino/issues/929
>     //ESP.deepSleep(0);
>     #if defined(STICK_C_PLUS)
>     axp192.PowerOff();
>     #elif defined(STICK_C_PLUS2)
>     digitalWrite(4,LOW);
>     #else
>     esp_deep_sleep_start();  // only wake up via hardware reset
>     #endif
>     return;
>   }
> ```
> 
> This fixed the problem here for me

ok, commit the changes

**Comment by bmorcelli** [comment]
In the line 10, include the libs like this:

```
#ifndef STICK_C_PLUS
  #include <ESP8266Audio.h>
  #include <ESP8266SAM.h>
#endif
```


Before starting the music command use:

```
#ifndef STICK_C_PLUS // at line ~203
  if(cmd_str.startsWith("music_player " ) || cmd_str.startsWith("tts" ) || cmd_str.startsWith("say" ) ) {
    // TODO: move in audio.cpp module

```

and after the code finish it with #endif, at line ~298 aproximately... the StickC Plus 1.1 binaty will be at 0x235000 size (fitting the target partition size of 0x260000

**Comment by eadmaster** [comment]
ok, so the music player is disabled  on the STICK_C_PLUS target.

**Pull request merged**
