### PR TITLE
Chameleon integration

### PR DESCRIPTION
**Pull request by rennancockles**
Integration with Chameleon Ultra device to emulate RFID

### CODE REVIEW

**Comment by eadmaster** [comment]
Chameleon Ultra is quite pricey, why not integrating somwthing like this instead?
https://github.com/Crypter/ESP-RFID
https://github.com/cmdwtf/Odiin

**Comment by IncursioHack** [comment]
> Chameleon Ultra is quite pricey, why not integrating somwthing like this instead? https://github.com/Crypter/ESP-RFID https://github.com/cmdwtf/Odiin

We extensively searched for ways to emulate RFID with the ESP32 (Bruce), unfortunately the overwhelming majority of chips and boards do not perform emulation, several possibilities were considered, including the use of the RFID present in the Flipper, however, we did not find the chip with a PCB to sale. T_T

There are some options as you mentioned, the choice of Chameleon was one because @rennancockles  has it and another because today it is the card with the highest reference on the market along with Proxmark.

**Comment by rennancockles** [comment]
@eadmaster because a chameleon is what I have at home to test. There's a low budget version that is not that pricey. This is the one I'm using

https://a.aliexpress.com/_mLKWIrK

I'm also working on some other integrations

**Comment by Ademolght** [comment]
> @eadmaster because a chameleon is what I have at home to test. There's a low budget version that is not that pricey. This is the one I'm using
> 
> https://a.aliexpress.com/_mLKWIrK
> 
> I'm also working on some other integrations

Can emulate miffare 1K , NTAG215 etc.... ?

**Pull request merged**
