### PR TITLE
fix qrcode and add more options

### PR DESCRIPTION
**Pull request by rennancockles**
Fix QRCode
Add Qrcode for 
- Bruce Repo
- PIX
- Custom text

### CODE REVIEW

**Comment by Niximkk** [comment]
pix?

shocked-computer

**Comment by Ademolght** [comment]
What is PIX?

**Comment by bmorcelli** [comment]
PIX is an electric/digital way to transfer money and pay bills in Brazil, with it you can leave your wallet at home and pay for stuff using your smartphone without using Credit card, and free of charges, because there's no taxes over these transactions..

**Comment by Ademolght** [comment]
Oh cool

**Pull request merged**
