### PR TITLE
Add RFID 125kHz reader

### PR DESCRIPTION
**Pull request by rennancockles**

### CODE REVIEW

**Comment by rennancockles** [comment]
rdm6300
RDM6300 connection schema

**Comment by achaoui** [comment]
Im new to bruce and this stuff, I bought the RDM6300 to read a tag, however with this schema, I couldnt read anything, so I swapped tx and rx over and finally I get data.
I am using M5StickCPlus2 with grove to dupont pins.
Thanks.

**Comment by EgorGoose** [comment]
Hello, is it planned to develop a 125Khz recording?

**Comment by reclaimerx10** [comment]
I have the CYD and want to add the RDM6300. Doni just hook it up the same as would be on the M5 stick (like corresponding lines) or just use the tx/rx same as the PN532? If not can it be added in the code

**Comment by EgorGoose** [comment]
Please add the 125 Khz recording capability

**Comment by ssawedoff** [comment]
Anyone having problems is most likely because you are hooking rx to rx and tx to tx when it should be rx to tx and tx to rx

**Comment by EgorGoose** [comment]
That's right, but I meant adding the ability to record keys at 125 Khz.

**Comment by enforcer2000** [comment]
Has anyone got this going with a T-embed c1101? I have tried attaching the RDM6300 to the left qwiic connector as per the pin outs on the C1101 github page:
https://github.com/Xinyuan-LilyGO/T-Embed-CC1101

I am using a qwiic connector to dupont connector cable - the RDM6300 illuminates and I have tried swapping rx and tx pins around for good measure to make sure I haven't got them backwards but am not able to read a 125khz tag that I know I can read with a cheap 125khz copier I bought off ebay. Any ideas?

These are the tags I have previously used to duplicate spares of the original rfid fob to show the spec I am referring to which I assume are just standard 125khz tags that the RDM6300 should be compatible with? The duplicates work fine on the door I am trying but I am trying to read the original tag rather than the re-writeable ones for the purposes of testing but assume it shouldn't make a difference:
https://www.amazon.co.uk/dp/B01K1TH8XQ/ref=pe_1909131_77697121_tnp_email_TE_AMZLdp_1?th=1

**Comment by Intorain** [comment]
> 但我正在尝试读取原始标签而不是可重写的标签以

你在亚马逊买的这个手环好像是不可写的ID标签，我在拼多多两块钱买了一个，这个是授权卡，不可写，只能授权使用。所以压根就不能复制。lilygo的这个C1101 有点操蛋，唯一的不足就是不能读写ID卡，还要额外插上ID卡读取设备。

**Comment by daniel2005d** [comment]
> Im new to bruce and this stuff, I bought the RDM6300 to read a tag, however with this schema, I couldnt read anything, so I swapped tx and rx over and finally I get data. I am using M5StickCPlus2 with grove to dupont pins. Thanks.

I'm making the connection as shown in the diagram and have swapped the wires, but it still doesn't work.

TX = G26
RX = G36 

And vice versa.


TX = G36
RX = G26

**Pull request merged**
