### PR TITLE
Html Portal

### PR DESCRIPTION
**Pull request by aleksfolt**
#### Proposed Changes ####

Added an HTML portal that allows the user to choose the access point name and upload specific HTML content. After selecting the access point, you can connect to it and navigate to the chosen IP address, where the uploaded HTML will be displayed. This feature can be useful for various purposes, such as games or content demonstration over local Wi-Fi.

#### Types of Changes ####

- New Feature (HTML portal)

#### Verification ####

The changes can be verified as follows:
1. Start the access point and select an HTML file to upload.
2. Connect to the created access point via Wi-Fi.
3. Open a browser and navigate to the access point's IP address to view the uploaded HTML content.

#### Testing ####

These changes are covered by testing the creation of the access point and the correct loading of HTML files. To verify, ensure that the HTML file is correctly displayed when connecting to the access point.

#### Linked Issues ####

This pull request is related to the task "Add HTML portal functionality" (#123) and the discussion in pull request #45.

#### User-Facing Change ####

```release-note
Added an HTML portal that allows users to choose an access point and upload HTML content for demonstration on a local device over Wi-Fi.

### CODE REVIEW

**Comment by bmorcelli** [comment]
EvilPortal already does that, doesn't it?

It lets you choose the wifi name
Lets you choose the Gateway IP address
And let you choose the html you want...

Sounds like duplicate functionality for me

**Comment by aleksfolt** [comment]
> EvilPortal already does that, doesn't it?
> 
> It lets you choose the wifi name
> Lets you choose the Gateway IP address
> And let you choose the html you want...
> 
> Sounds like duplicate functionality for me

No, it displays the selected page only when attempting to connect to Wi-Fi, but it’s not possible to access the page from the browser. This is not very efficient, especially considering that some phones simply disconnect you from Wi-Fi due to a timeout. In this version, a web portal opens, and you can connect to the site through the browser.

**Comment by Ademolght** [comment]
@pr3y merge it it's a good thing

**Comment by bmorcelli** [comment]
So, the idea is it **not work as a Captive portal**.. just serve the html content on an IP address?

**Comment by aleksfolt** [comment]
> So, the idea is it **not work as a Captive portal**.. just serve the html content on an IP address?

Well.. Yeah, I thought it would complement the firmware well.

**Comment by pr3y** [comment]
This functionality "HTML Portal" will not be merged to main since it kinda misses on impact and there is already a way to achieve the same results (like EvilPortal).
Also we believe much more can be achieved in the future with the [Interpreter](https://github.com/pr3y/Bruce/wiki/Interpreter), to work on some function to render like webUI.

**Pull request closed without merging**
