### PR TITLE
fix CYD GPS

### PR DESCRIPTION
**Pull request by shnmorimoto**
#### Proposed Changes ####

Bugfix for GPS on CYD

ref #352

#### Types of Changes ####

Bugfix

#### Verification ####

Verify Wardriving is work on CYD with NEO-6M

#### Testing ####

I tested it on 2432S028R

IMG_0131

Since it is indoors, it is displayed as not updated, but when it is outdoors, the location can be obtained successfully.
And the wardriving.csv was created successfully.

#### Linked Issues ####

ref #352 

#### User-Facing Change ####

```release-note
NONE
```

#### Further Comments ####

Modified with reference to the following.

https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/blob/d81d8ffdf207d8549c271f11a99e98dc7727ce67/esp32_marauder/GpsInterface.cpp#L28

### CODE REVIEW

**Comment by shnmorimoto** [comment]
I haven't been able to consider other boards, so I'll do some more testing...

**Comment by bmorcelli** [comment]
I believe it would be easier change the values on platformio.ini than changing here, because I think it will break the m5 gps communication (I think, will test if the original option works this night)

**Comment by shnmorimoto** [comment]
@bmorcelli Thank you. I definitely think that's the better way.
I would like to close this PR and create a new PR again after changing the interface you are working on.

**Comment by bmorcelli** [comment]
Ok, Thank you!

I will change these values here, in advance.. 

But will count with your additions into the Capacitive CYD port here:

https://github.com/bmorcelli/Bruce/tree/interface/ports/CYD-2432S028

**Comment by shnmorimoto** [comment]
Thank you! I got it!

**Pull request closed without merging**
